# Colors (Snazzy)
colors:
  # Default colors
  primary:
    background: "#282a36"
    foreground: "#eff0eb"

  # Normal colors
  normal:
    black: "#282a36"
    red: "#ff5c57"
    green: "#ffffaf"
    #green: "#ffbbff"
    yellow: "#f3f99d"
    blue: "#57c7ff"
    magenta: "#ff6ac1"
    cyan: "#9aedfe"
    white: "#f1f1f0"

  # Bright colors
  bright:
    black: "#686868"
    red: "#ff5c57"
    green: "#5af78e"
    yellow: "#f3f99d"
    blue: "#57c7ff"
    magenta: "#ff6ac1"
    cyan: "#9aedfe"
    white: "#f1f1f0"

# Font configuration (changes require restart)
font:
  # Normal (roman) font face
  normal:
    family: FiraCode Nerd Font Mono

  # Bold font face
  bold:
    family: FiraCode Nerd Font Mono

  # Point size
  size: 10.0

# 背景不透明度
background_opacity: 0.95

