#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

/bin/bash ~/scripts/autostart-common.sh &
/bin/bash ~/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color  \#FFFFFF

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled


# 解决部分java gui程序（例如Intellij的IDE）不显示任何内容的问题
wmname LG3D

